version: '1'
services:
  mongodb:
    image: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=rocf-db
      - MONGO_INITDB_ROOT_USERNAME=rocf-admin
      - MONGO_INITDB_ROOT_PASSWORD=ASAHDHAFIDFOIAI
    volumes:
      - mongo-volume:/data/db
    ports:
      - 27018:27017
volumes:
  mongo-volume:
    driver: local
